#pragma once

#define RPC_OK 0x00
#define RPC_INVALID_PCODE 0x01
#define RPC_NET_ERR 0x02
#define RPC_OVERFLOW 0x03
#define RPC_SEND_AFTER_EOF 0x04
#define RPC_RECV_BEFORE_EOF 0x05
#define RPC_RECV_DUPLICATE 0x06