
config_setting(
  name = "pnrpc_use_boost_asio",
  define_values = {"pnrpc_use_boost_asio" : "true"}
)

config_setting(
  name = "pnrpc_use_boost_mysql",
  define_values = {"pnrpc_use_boost_mysql" : "true"}
)

config_setting(
  name = "pnrpc_use_boost_redis",
  define_values = {"pnrpc_use_boost_redis" : "true"}
)